### 3.微博详情页功能测试
GET http://localhost:8080/v1/weibo/selectById?id=200
Accept: application/json


### 2.微博首页列表展示功能测试
GET http://localhost:8080/v1/weibo/selectIndex
Accept: application/json


### 1.发布微博功能测试
POST http://localhost:8080/v1/weibo/insert
Content-Type: application/json

{
  "content": "我坚信任何困难都难不倒英雄的中国人民！"
}

