### 5.根据id查询用户信息测试[@PathVariable注解]
GET http://localhost:8080/v1/users/selectById/1
Accept: application/json

### 4.修改用户测试
POST http://localhost:8080/v1/users/update
Content-Type: application/x-www-form-urlencoded

id=1&username=GPT&password=123456&nickname=gpt

### 3.删除用户测试
GET http://localhost:8080/v1/users/delete?id=2
Accept: application/json

### 2.用户列表测试
GET http://localhost:8080/v1/users/userList
Accept: application/json

### 1.添加用户测试
POST http://localhost:8080/v1/users/insert
Content-Type: application/x-www-form-urlencoded

username=Shasha&password=123456&nickname=shasha
